AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Contains isAddressInAirdropFunction, refreshXSLockCache and getXSLocks lambdas

Transform:
- AWS::Serverless-2016-10-31

Resources:
  isAddressInAirdropFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/isAddressInAirdrop/index.isAddressInAirdropHandler
      Runtime: nodejs14.x
      FunctionName: isAddressInAirdropFunction
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function takes an Ethereum address, returns true if address in airdrop and false otherwise
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /airdrop/{address}
            Method: GET

  xsLockCache:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: xs-lock-cache

  refreshXSLockCache:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/xsLockCache/refreshXSLockCache.refreshXSLockCacheHandler
      Runtime: nodejs14.x
      FunctionName: refreshXSLockCache
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function which refreshes the xsLock cache
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref xsLockCache
      Environment:
        Variables:
          BUCKET: !Ref xsLockCache
          BUCKET_KEY: xsLockersCache.json
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0/3 * * * ? *)

  getXSLock:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/xsLockCache/getXSLocks.getXSLocksHandler
      Runtime: nodejs14.x
      FunctionName: getXSLocks
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function which gets the xsLocks for an address
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref xsLockCache
      Environment:
        Variables:
          BUCKET: !Ref xsLockCache
          BUCKET_KEY: xsLockersCache.json
      Events:
        Api:
          Type: Api
          Properties:
            Path: /xslocks/{address}
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for isAddressInAirdrop lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"